### Create a post
POST {{urlPosts}}
Content-Type: application/json

{
  "title": "Test Title",
  "body": "Test blog post body"
}

### Post error
POST {{urlPosts}}
Content-Type: application/json

{
  "title": 123,
  "body": 123
}
